#!/usr/bin/env ruby

require 'English'
require 'io/console'
require 'shellwords'
require 'tempfile'

require 'simple_scripting/argv'
require 'simple_scripting/configuration'

require_relative "#{File.basename(__FILE__)}.lib/replan_helper"

require_relative "#{File.basename(__FILE__)}.lib/relister"
require_relative "#{File.basename(__FILE__)}.lib/refixer"
require_relative "#{File.basename(__FILE__)}.lib/readder"
require_relative "#{File.basename(__FILE__)}.lib/replanner"
require_relative "#{File.basename(__FILE__)}.lib/retemplater"
require_relative "#{File.basename(__FILE__)}.lib/reworker"
require_relative "#{File.basename(__FILE__)}.lib/remover"

def conditional_save(content, original_content, schedule_filename, archive_filename, compare: false, move:)
  if content != original_content
    if compare
      updated_file = Tempfile.new('new').path
      IO.write updated_file, content
      `meld #{schedule_filename.shellescape} #{updated_file.shellescape}`

      puts "Press `y` to commit the changes!"
      confirm_commit = $stdin.getch
    else
      confirm_commit = "y"
    end

    if confirm_commit == "y"
      if move
        Remover.new.execute(schedule_filename, archive_filename, content)
      else
        IO.write(schedule_filename, content)
      end
    else
      puts "", "Changes not committed!"
    end
  else
    puts "No changes!"
  end
end

class Replan
  def list(schedule_filename, json:)
    content = IO.read(schedule_filename)

    Relister.new.execute(content, json: json)
  end

  def update(schedule_filename, archive_filename, template_filename:, compare:, move:, debug:)
    content = IO.read(schedule_filename)
    original_content = content.dup

    content = Refixer.new.execute(content)
    content = Readder.new.execute(content)
    content = Retemplater.new(template_filename).execute(content) if template_filename && move
    content = Reworker.new.execute(content) if move
    content = Replanner.new.execute(content, debug: debug)

    conditional_save(content, original_content, schedule_filename, archive_filename, compare: compare, move: move)
  end
end

if __FILE__ == $PROGRAM_NAME
  options = SimpleScripting::Argv.decode(
    [ "-d", "--debug",     "Debug mode" ],
    [ "-c", "--compare",   "Compare before replacing the file, if there is any change, and ask confirmation" ],
    [ "-l", "--list",      "List mode (limited to #{Relister::DEFAULT_DAYS_LISTED} days)"],
    [ "-j", "--json",      "Set JSON output for list mode (no limits)"],
    [ "-M", "--nomove",    "Don't move the current day after applying the replans"],
    [ "-w", "--work",      "Compute the work hours for the current day"],
  ) || exit

  configuration = SimpleScripting::Configuration.load
  schedule_filename = configuration.schedule_filename.full_path
  list = !!options[:list]
  work = !!options[:work]
  debug_mode = options.delete(:debug)
  json = options.delete(:json)

  begin
    if list
      raise "List mode is not compatible with other options" if options.size > 1

      Replan.new.list(schedule_filename, json: !!json)
    else
      raise "JSON output is valid only in list mode" if json

      if work
        content = IO.read(schedule_filename)
        work_hours = Reworker.new.compute_first_date_work_hours(content)
        puts "Work hours: #{work_hours}"
      else
        archive_filename = configuration.archive_filename.full_path
        template_filename = configuration.template_filename&.full_path
        move = !options[:nomove]
        compare = !!options[:compare]

        Replan.new.update(schedule_filename, archive_filename, template_filename: template_filename, compare: compare, move: move, debug: debug_mode)
      end
    end
  rescue => error
    if debug_mode
      raise error
    else
      puts error
      exit 1
    end
  end
end
