#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.6.2
# from Racc grammar file "".
#

require 'racc/parser.rb'

  require 'ostruct'

  require_relative 'replan_lexer'

class ReplanParser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 45)
  attr_accessor :v_f, :v_f_time, :v_s, :v_ul, :v_uu, :v_interval, :v_next_prefix, :v_next

  def parse(input)
    scan_str(input)

    OpenStruct.new(
      fixed:       self.v_f,
      fixed_time:  self.v_f_time,
      skip:        self.v_s,
      update:      self.v_ul,
      update_full: self.v_uu,
      interval:    self.v_interval,
      next_prefix: self.v_next_prefix,
      next:        self.v_next,
    )
  end

  private

  # Assign to self.<var>, checking that it's not already assigned.
  #
  def checked_assign(var, value)
    self.send(var).nil? ?
      self.send("#{var}=", value) :
      raise("Option '#{var}' is already assigned: #{self.send(var)}")
  end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    14,    15,    16,    17,    19,    20,    21,     9,     2,    10,
    11,    12,     9,     3,    10,    11,    12,    19,    20,     4,
     5,    23,    24,    25,    27 ]

racc_action_check = [
     6,     6,     6,     6,     6,     6,     7,     7,     0,     7,
     7,     7,     4,     1,     4,     4,     4,    24,    24,     2,
     3,     9,    14,    19,    25 ]

racc_action_pointer = [
     6,    13,    16,    20,     8,   nil,    -9,     3,   nil,    16,
   nil,   nil,   nil,   nil,    19,   nil,   nil,   nil,   nil,    20,
   nil,   nil,   nil,   nil,     4,    15,   nil,   nil ]

racc_action_default = [
   -19,   -19,   -19,   -19,    -2,    28,   -19,   -19,    -5,    -6,
    -8,    -9,   -10,    -1,   -11,   -13,   -14,   -15,   -16,   -19,
   -18,    -3,    -4,    -7,   -19,   -19,   -12,   -17 ]

racc_goto_table = [
    18,     8,     1,     6,    22,    13,     7,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    26 ]

racc_goto_check = [
     6,     5,     1,     2,     5,     3,     4,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     6 ]

racc_goto_pointer = [
   nil,     2,    -1,    -1,     2,    -3,    -6 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  4, 16, :_reduce_none,
  0, 17, :_reduce_none,
  2, 17, :_reduce_none,
  2, 19, :_reduce_none,
  1, 19, :_reduce_none,
  1, 20, :_reduce_6,
  2, 20, :_reduce_7,
  1, 20, :_reduce_8,
  1, 20, :_reduce_9,
  1, 20, :_reduce_10,
  1, 18, :_reduce_11,
  3, 18, :_reduce_12,
  1, 18, :_reduce_13,
  1, 18, :_reduce_14,
  1, 18, :_reduce_15,
  1, 18, :_reduce_none,
  3, 21, :_reduce_17,
  1, 21, :_reduce_18 ]

racc_reduce_n = 19

racc_shift_n = 28

racc_token_table = {
  false => 0,
  :error => 1,
  :REPLAN => 2,
  :WHITESPACE => 3,
  :F => 4,
  :TIME => 5,
  :S => 6,
  :U_LOW => 7,
  :U_UP => 8,
  :INTERVAL => 9,
  :LAST_DAY => 10,
  :LAST_DAYNUM => 11,
  :FIRST_DAY => 12,
  :IN => 13,
  :DAY => 14 }

racc_nt_base = 15

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "REPLAN",
  "WHITESPACE",
  "F",
  "TIME",
  "S",
  "U_LOW",
  "U_UP",
  "INTERVAL",
  "LAST_DAY",
  "LAST_DAYNUM",
  "FIRST_DAY",
  "IN",
  "DAY",
  "$start",
  "expression",
  "options_r",
  "period_and_next",
  "options",
  "option",
  "next" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

module_eval(<<'.,.,', 'parser.y', 16)
  def _reduce_6(val, _values, result)
     checked_assign(:v_f, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_7(val, _values, result)
     checked_assign(:v_f, val.fetch(0)); checked_assign(:v_f_time, val.fetch(1))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 18)
  def _reduce_8(val, _values, result)
     checked_assign(:v_s, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 19)
  def _reduce_9(val, _values, result)
     checked_assign(:v_ul, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 20)
  def _reduce_10(val, _values, result)
     checked_assign(:v_uu, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 24)
  def _reduce_11(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 25)
  def _reduce_12(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 26)
  def _reduce_13(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_14(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 28)
  def _reduce_15(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

# reduce 16 omitted

module_eval(<<'.,.,', 'parser.y', 33)
  def _reduce_17(val, _values, result)
     self.v_next_prefix = val.fetch(0); self.v_next = val.fetch(2)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 34)
  def _reduce_18(val, _values, result)
     self.v_next = val.fetch(0)
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class ReplanParser
